SELECT* FROM employee_1
--ALTER DATATYPE LIKE ONE DATA TYPE TO ANOTHER DATA TYPE 
ALTER TABLE employee_1 ALTER COLUMN NAME NVARCHAR (20)
--IF WE WANT TO PROVIED A NEW VALUE TO THE ROW 
UPDATE EMPLOYEE_1 SET NAME= N'अनंत' WHERE id=3
-- ADD NEW COLUMN IN A TABLE 
ALTER TABLE  EMPLOYEE_1 ADD  GMAIL VARCHAR(50)
UPDATE  EMPLOYEE_1 SET GMAIL= 'AMIT@9936GMAIL.COM' WHERE ID=3 AND ID=6
--IF WE WANT TO CHANGE THE NAME OF THE COULMN \
--##MOST IMPORTANT 
EXEC sp_rename 'EMPLOYEE_1.GMAIL', 'G_MAIL', 'COLUMN';