
SELECT  ID,	name,	salary,	start_date,	city,region, 
CONCAT(ID,	name,	salary,	start_date,city,region) ALL_COLUMN
from  with_else WHERE ID=1
SELECT  ID,	name,	salary,	start_date,	region,city, 
CONCAT(ID,	name,	salary,	start_date, region,city) ALL_COLUMN
from  with_else WHERE ID=1
1Jason40420Feb  1 1994 12:00AMNeYorkW w
1Jason40420Feb  1 1994 12:00AMNew York

SELECT *,CONCAT(FNAME,' ',LNAME) CONCAT_FULL_NAME,
COALESCE(FNAME,LNAME)  AS COALESCE1,
NULLIF(FNAME,LNAME) AS NULLIFCON,
NULLIF(FNAME,'MALL') AS NULLIFCON,
FNAME+LNAME,
ISNULL(FNAME,'UNKNOWN') AS ISNULL1,
COALESCE(FNAME,'N/A') AS COALESCE_REPLACENULLVALUE
FROM(
SELECT 1 ID, 'sANJAY' FNAME,NULL AS LNAME
UNION
sELECT NULL, 'MALL' ,'SINGH' AS LNAME
UNION
SELECT 2, NULL,'GUPTA' AS LNAME
UNION
SELECT 3, NULL,NULL AS LNAME
UNION
SELECT 3, 'MALL','MALL' AS LNAME
) TBL
select * frome table 
  
