CREATE DATABASE AMIT
CREATE TABLE EMP_AMIT (
    emp_id INT PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(70)
);
INSERT INTO EMP_AMIT (emp_id,name,email) VALUES 
(1, 'Amit', 'amit@test.com'),
(2, 'Ritika', 'ritika@test.com');
SELECT * FROM EMP_AMIT

-- IF YOU WANT TO DROP DATABASE 
-- ##DROP DATABASE DATABASE_NAME
DROP DATABASE AMIT -- THIS DATA BASE IS ALREADY DELETE 

-- IF YOU WANT TO DROP A TABLE 
DROP TABLE AMIT

-- IF YOU WANT TO DROP A COLUMN 
ALTER TABLE EMP_AMIT 
DROP COLUMN EMAIL