-- LEFT JOIN BASED QUESTION 

SELECT  * FROM STUDENT_0
SELECT* FROM StudentCourse

SELECT S. ROLL_NO, S.NAME , S.PHONE, C.COURSE_ID FROM STUDENT_0 S
LEFT JOIN 
STUDENTCOURSE AS C
ON S.ROLL_NO =C. ROLL_NO 


-- LEFT OUTER JOIN 
SELECT  * FROM STUDENT_0
SELECT* FROM StudentCourse
SELECT S. ROLL_NO, S.NAME , S.PHONE, C.COURSE_ID FROM STUDENT_0 S
LEFT OUTER JOIN 
STUDENTCOURSE AS C
ON S.ROLL_NO =C. ROLL_NO 

--RIGHT JOIN 
SELECT  * FROM STUDENT_0
SELECT* FROM StudentCourse
SELECT S. ROLL_NO, S.NAME , S.PHONE, C.COURSE_ID FROM STUDENT_0 S
RIGHT JOIN 
STUDENTCOURSE AS C
ON S.ROLL_NO =C. ROLL_NO 
-- SOLVING THIS PROBLEM YOU CAN SAY THAT LEFT JOIN IS EQUAL TO LEFT OUTER JOIN 


-- RIGHT OUTER JOIN 
SELECT  * FROM STUDENT_0
SELECT* FROM StudentCourse
SELECT S. ROLL_NO, S.NAME , S.PHONE, C.COURSE_ID FROM STUDENT_0 S
RIGHT  OUTER JOIN 
STUDENTCOURSE AS C
ON S.ROLL_NO =C. ROLL_NO 

-- SOLVING THIS PROBLEM YOU CAN SAY THAT RIGHT JOIN IS EQUAL TO RIGHT OUTER JOIN 

SELECT  * FROM STUDENT_0
SELECT* FROM StudentCourse
SELECT S. ROLL_NO, S.NAME , S.PHONE, C.COURSE_ID FROM STUDENT_0 S
FULL JOIN 
STUDENTCOURSE AS C
ON S.ROLL_NO =C. ROLL_NO 

