DECLARE @SAL INT;
SET @SAL=2;

WITH SAL AS(

SELECT *, 
--ROW_NUMBER TO FIND OR DELETE DUPLICATE RECORDS ON BEHLAF HALF COLUMN OR GROUP
ROW_NUMBER() OVER(PARTITION BY Empcode ORDER BY SALARY) ROW_NUM
--DENSE_RANK TO FIND HIGHEST SALARY ON BEHLAF HALF COLUMN OR GROUP
, DENSE_RANK() OVER(PARTITION BY Empcode ORDER BY SALARY) DNS_RNK

, RANK() OVER(PARTITION BY Empcode ORDER BY SALARY) RNK
FROM SalaryDetail
)
SELECT * FROM SAL WHERE DNS_RNK=@SAL
