
DECLARE @ROW_NUM1 INT;
SET @ROW_NUM1=10;

WITH INVOICE as
(
select *,
ROW_NUMBER() OVER(PARTITION BY INVO_ID,ORDER_ID ORDER BY ORDER_ID) AS ROW_NUM,
ROW_NUMBER() OVER(ORDER BY INVO_ID) AS ROW_NUM1,
DENSE_RANK() OVER(PARTITION BY  INVO_ID,ORDER_ID ORDER BY ORDER_ID) AS DENS_RNK,
DENSE_RANK() OVER(ORDER BY INVO_ID) AS DENS_RNK1
from INVOICES
)
select * from INVOICE
WHERE ROW_NUM1=@ROW_NUM1

WHERE ROW_NUM1=
select * from #emp
select * from ##emp
