USE [COLLEGE];
go
CREATE TABLE ORDERS (
ORDER_ID INT ,
CUST_NAME VARCHAR (20));
INSERT INTO ORDERS (ORDER_ID, CUST_NAME) 
VALUES 
(1, 'AMIT' ),
(2, 'NIKHIL'),
(3,'ABHAY'),
(4,'ABHAYYADAV'),
(5,'ABHAYSINGH');   

CREATE TABLE INVOICES (
INVO_ID  INT NOT NULL ,
ORDER_ID INT ,
STATUS VARCHAR (20));
INSERT INTO INVOICES (INVO_ID, ORDER_ID, STATUS)
VALUES
(05, 1, 'PAID'),
(06, 1, 'PAID'),
(06, 2, 'PAINDING'),
(08, 4, 'PAID');
SELECT ORD.ORDER_ID, ORD.CUST_NAME, COALESCE (INV.STATUS , 'NO INVOICE'),
ISNULL (INV.STATUS , 'NO INVOICE')
STATUS FROM ORDERS AS ORD
LEFT JOIN INVOICES AS INV ON INV.ORDER_ID = ORD.ORDER_ID 
WHERE INV.STATUS != 'PAID' OR INV.STATUS IS NULL

DROP TABLE INVOICES


select * from ORDERS
select * from INVOICES
ORDER BY INVO_ID
alter table INVOICES add  primary key  (INVO_ID)

DROP TABLE INVOICES;
TRUNCATE TABLE INVOICES 

delete from INVOICES
WHERE INVO_ID=1
WITH INVOICE as
(
select *,
ROW_NUMBER() OVER(PARTITION BY INVO_ID,ORDER_ID ORDER BY ORDER_ID) AS ROW_NUM,
ROW_NUMBER() OVER(ORDER BY INVO_ID) AS ROW_NUM1,
RANK() OVER(PARTITION BY  INVO_ID,ORDER_ID ORDER BY ORDER_ID) AS RAN,
RANK() OVER( ORDER BY INVO_ID) AS RAN1,
DENSE_RANK() OVER(PARTITION BY  INVO_ID,ORDER_ID ORDER BY ORDER_ID) AS DENS_RNK,
DENSE_RANK() OVER(ORDER BY INVO_ID) AS DENS_RNK1
from INVOICES
)
select * from INVOICE
where ROW_NUM>1
where 
ORDER_ID
1